name: Deploy Node.js App to Cpanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Cpanel
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: server35.integrator.com.br
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        local-dir: ./
        server-dir: /applications/

    - name: Start application with PM2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key_zonu
        chmod 600 ~/.ssh/key_zonu
        ssh-keyscan -H 'server35.integrator.com.br' >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/key_zonu -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@server35.integrator.com.br -p 22 'pm2 start applications/zonuserver/server.js'
      env:
        SSH_PORT: 22
